// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOPbIm9hgT7ZF_kO5bJ6WzAs1Cti597EI',
    appId: '1:722753961909:web:b528ce8458fd8ce38f23fc',
    messagingSenderId: '722753961909',
    projectId: 'bookswap-45220',
    authDomain: 'bookswap-45220.firebaseapp.com',
    storageBucket: 'bookswap-45220.firebasestorage.app',
    measurementId: 'G-RNRCZ748LD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV3w7DCbYew_CHS0rIE4uoxLgLbzd2NQY',
    appId: '1:722753961909:android:5fdb188adbae60468f23fc',
    messagingSenderId: '722753961909',
    projectId: 'bookswap-45220',
    storageBucket: 'bookswap-45220.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWTMVnjZhaHDsx75unwDe39iun5DOHTfw',
    appId: '1:722753961909:ios:9db58db27362a0948f23fc',
    messagingSenderId: '722753961909',
    projectId: 'bookswap-45220',
    storageBucket: 'bookswap-45220.firebasestorage.app',
    iosBundleId: 'com.example.bookswapApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'your-macos-api-key',
    appId: 'your-macos-app-id',
    messagingSenderId: 'your-sender-id',
    projectId: 'your-project-id',
    storageBucket: 'your-project-id.appspot.com',
    iosBundleId: 'com.example.bookswapApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'your-windows-api-key',
    appId: 'your-windows-app-id',
    messagingSenderId: 'your-sender-id',
    projectId: 'your-project-id',
    authDomain: 'your-project-id.firebaseapp.com',
    storageBucket: 'your-project-id.appspot.com',
  );
}